services:
    jgm.table.twig:
        class: JGM\TableBundle\Twig\TableExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    jgm.table:
        class: JGM\TableBundle\Table\TableFactory
        scope: request
        arguments: ["@service_container","@doctrine.orm.entity_manager","@request","@router"]
    jgm.url_helper:
        class: JGM\TableBundle\Table\UrlHelper
        scope: request
        arguments: ["@request","@router"]