services:
    jgm.url_helper:
        class: JGM\TableBundle\Table\Utils\UrlHelper
        arguments: ["@request_stack","@router"]
    jgm.table_context:
        class: JGM\TableBundle\DependencyInjection\Service\TableContext
    jgm.table_collector:
        class: JGM\TableBundle\DataCollector\TableCollector
        arguments: ["@jgm.table_context","@jgm.table_stopwatch"]
        public: false
        tags:
            - { name: data_collector, template: 'JGMTableBundle:DataCollector:table_collector', id: 'jgm.table_collector' }
    jgm.table_stopwatch:
        class: JGM\TableBundle\DependencyInjection\Service\TableStopwatchService
        arguments: ["%kernel.debug%"]
    jgm.table_factory:
        class: JGM\TableBundle\DependencyInjection\Service\TableFactoryService
        arguments: ["@service_container","@doctrine.orm.entity_manager","@request_stack","@router","@logger","@jgm.table_stopwatch"]
        tags:
            - { name: jgm.table, channel: jgm }
    jgm.table: '@jgm.table_factory'
    jgm.table.twig.attributes_formater:
        class: JGM\TableBundle\Twig\AttributesFormaterExtension
        tags:
            - { name: twig.extension }
    jgm.table.twig:
        class: JGM\TableBundle\Twig\TableExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig.order:
        class: JGM\TableBundle\Twig\OrderExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
    jgm.table.twig.pagination:
        class: JGM\TableBundle\Twig\PaginationExtension
        arguments: ["@jgm.url_helper", "@jgm.table_stopwatch"]
        tags:
            - { name: twig.extension }
