services:
    pzad.table.twig:
        class: PZAD\TableBundle\Twig\TableExtension
        arguments: ["@service_container","@router"]
        tags:
            - { name: twig.extension }
    pzad.table:
        class: PZAD\TableBundle\Table\TableFactory
        scope: request
        arguments: ["@service_container","@doctrine.orm.entity_manager","@request","@router"]